services:
  # Backend Service
  - type: web
    name: nexora-backend
    runtime: node
    region: singapore # Optional: defaults to Oregon, adjust as needed
    plan: free # Optional: defaults to starter
    rootCommand: cd backend
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false


staticSites:
  # Frontend Service (Static Site)
  - name: nexora-frontend
    rootCommand: cd frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: nexora-backend
          property: url
